#   Copyright DataStax, Inc.
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#   http://www.apache.org/licenses/LICENSE-2.0
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

name: Docker Image CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run cassandra
      run: docker run -d -P --name test-cassandra cassandra:3.11.6
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: build
      run: mvn package
    - name: stop cassandra
      run: docker kill test-cassandra && docker rm test-cassandra
    - name: build and push github package
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ github.token }}
        registry: docker.pkg.github.com
        repository: datastax/stargate/stargate
        dockerfile: kube/Dockerfile
        tag_with_ref: true
    - name: build and push docker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.STARGATE_DOCKER_USER }}
        password: ${{ secrets.STARGATE_DOCKER_PASSWORD }}
        repository: datastax/stargate
        dockerfile: kube/Dockerfile
        tag_with_ref: true
